### ISSUE TITLE
"Removed or no access" Is this still available on Terra?

### ISSUE THREAD

**Issue by VitaminBrad** [aryeelab/dna-methylation-tools#2]
Hello, I cloned the workspace and got this when I began a workflow: ![71005915-7D9F-4C3C-8EFC-58E8099A4849](https://user-images.githubusercontent.com/5053928/127365709-9b519af3-c80a-42bb-8b5f-2dbad68cc7f6.png)
![D5473784-1F4E-4B3F-A411-891EDBAC4247](https://user-images.githubusercontent.com/5053928/127365719-14ca2230-48f2-469a-8275-31f43ce9d290.png)

Thanks!

**Comment by VitaminBrad** [comment]
Here is an accompanying error. 

Thanks for any help whatsoever!
![Screenshot 2021-07-31 12 04 12 PM](https://user-images.githubusercontent.com/5053928/127745731-375f9ab1-01fd-440d-b83a-5798cd895603.png)

**Comment by divy-kangeyan** [comment]
Hi @VitaminBrad I am not currently affiliated with Broad. I can email you some contacts who could be able to help out.

Divy

**Comment by martinaryee** [comment]
Apologies for missing this! The workspace is available here: https://app.terra.bio/#workspaces/aryee-lab/bisulfite-seq-tools-grch38

Please let us know if you're still interested in trying it out.

**Comment by VitaminBrad** [comment]
Roger that! 

All sorted now. 

Thanks!
